### ISSUE TITLE
Plots Overlapping: Separate Model Evaluation Plots into Individual Figures

### ISSUE THREAD

**Issue by yashasvini121** [yashasvini121/predictive-calc#1]
Currently, in the ModelEvaluation class, the plots generated for model evaluation (e.g., accuracy, confusion matrix) are being attached together on the same figure. This leads to overlapping visualizations, making it difficult to view the plots individually.

Expected Behavior: Each plot should be displayed in its own figure, with the ability to view them separately.

Actual Behavior: Multiple plots are attached together on a single figure.

Issue screenshot:
![image](https://github.com/user-attachments/assets/a0f3ca53-deb9-4809-9619-6e24180fafce)

**Comment by ChitteshKumar** [comment]
Hi, @yashasvini121 I am interested in fixing this issue. I will be grateful if you assign this to me.

**Comment by yashasvini121** [comment]
Assigned 👍

**Comment by apoorvxgoyalx** [comment]
hi @yashasvini121 I am interested in fixing this issue

**Comment by yashasvini121** [comment]
Hi @apoorvxgoyalx, this issue is already assigned. For now, you can work on the other issues.

**Comment by ChitteshKumar** [comment]
@yashasvini121 Hi, I have completed the issue and raised a PR can you check that and accept then we can close this issue. Thank you
