### ISSUE TITLE
Adding BMI calculator and predicting whether the person is healthy or not

### ISSUE THREAD

**Issue by JOSHITHA6** [yashasvini121/predictive-calc#115]
🌟 **Is your feature request related to a problem?**:
 Nowadays people are focussed on calculating their health BMI. So, this additional feature to your project would be really helpful for people of all ages 

💡 **Describe the solution you'd like**:
 I would like to add a person's age and weight and mention 3 categories like overweight, underweight and normal(healthy). Based on the threshold value, if the weight crosses normal limit, person will be classified as overweight, if he crosses less than actual weight needed, he will be classified as underweight, if he/she meets required range of normal stage, he/she will be classifies as healthy.

**To be Mentioned while taking the issue**:
- What is your participant role?  My role is an open-source contributed and add Gssoc'24 extd, hacktoberfest 

**Note:**
- Please review the project documentation and ensure your code aligns with the project structure.
- Please ensure that either the `predict.py` file includes a properly implemented `model_details()` function or the notebook contains this function to print a detailed model report. The model will not be accepted without this function in place, as it is essential for generating the necessary model details.
- Prefer using a new branch to resolve the issue, as it helps keep the main branch stable and makes it easier to manage and review your changes.
- Strictly use the pull request template provided in the repository to create a pull request.

Please assign this task to me @yashasvini121 under gssoc'24 extd and hacktoberfest

**Comment by Dipak7781** [comment]
Please Assign this task to me @yashasvini121 under gssoc'24 extd

**Comment by yashasvini121** [comment]
Sure @JOSHITHA6 go ahead!

**Comment by Nikita-Kulshrestha** [comment]
Please Assign this task to me @yashasvini121 under gssoc'24 extd
I found @JOSHITHA6's approach quite insightful and I would like to try something on the similar lines :)

**Comment by yashasvini121** [comment]
@JOSHITHA6, could you please clarify if your idea involves an ML model?

**Comment by yashasvini121** [comment]
> Please Assign this task to me @yashasvini121 under gssoc'24 extd I found @JOSHITHA6's approach quite insightful and I would like to try something on the similar lines :)

Please clarify your idea and create a new issue for it. @Nikita-Kulshrestha

**Comment by Nikita-Kulshrestha** [comment]
> > Please Assign this task to me @yashasvini121 under gssoc'24 extd I found @JOSHITHA6's approach quite insightful and I would like to try something on the similar lines :)
> 
> Please clarify your idea and create a new issue for it. @Nikita-Kulshrestha

Why I Want to Work on This Issue:
Health and fitness are important aspects of everyday life, and providing a simple yet effective tool like a BMI calculator is an excellent and simple way for people to judge the initial fitness levels. Additionally, I plan to integrate some health tips pertaining to dietary measures and exercise routines offering a more holistic approach, without demotivating them, hence offering a more user-centric design.

Approach:
I will create a function that calculates BMI based on the user’s weight and height inputs.
Health Prediction Based on BMI: I  would like to research on how people are categorized into overweight/underweight/normal weight and based on that, provide them with a few tips and some pepping up messages along with the BMI output they receive.

User Experience:
Input from user will be validated (only positive numbers allowed), and error messages in other cases
The user interface will focus on clean design, using visual cues like color-coded feedback (would still be exploring the option of using colorama library to show the user's health status.

**Comment by yashasvini121** [comment]
This BMI calculator isn't needed as it doesn't involve an ML model. Therefore, I am closing this issue for now.

**Comment by Nikita-Kulshrestha** [comment]
@yashasvini121 I was not aware you were specifically looking for ML integration. 
My new approach would be to include an ML model in the BMI calculator for health prediction, you can create a model that learns from health-related datasets (e.g., BMI, age, gender, lifestyle factors) and predicts whether a person is healthy or at risk. 
If you're still willing to re-open this issue, i could elaborate :)

**Comment by yashasvini121** [comment]
Sure @Nikita-Kulshrestha, you can work on it if you'd like. However, after the final review, I'll decide whether it qualifies as a proper ML model and if it should be merged.

**Comment by Nikita-Kulshrestha** [comment]
@yashasvini121 How do i show you the code ive written? could i have your gmail address or something please?

**Comment by Nikita-Kulshrestha** [comment]
> Sure @Nikita-Kulshrestha, you can work on it if you'd like. However, after the final review, I'll decide whether it qualifies as a proper ML model and if it should be merged.

I've worked on this issue in a Google colab file and wish to show it to you

**Comment by yashasvini121** [comment]
> I've worked on this issue in a Google colab file and wish to show it to you

@Nikita-Kulshrestha  Sure! You can share your Colab with me, but first, please review the `docs/` folder to understand the project structure and the steps for adding your model to the existing framework.

Have you forked the repository? If not, please do so and create a new branch with any name, like `<bmi>`. Instead of sharing the Colab directly, you can organize your work by creating a new model folder and uploading your notebook under the appropriate path.  

For example:
```
models/bmi_predictor/notebooks/<your_file>.ipynb
```

Let me know if you have any other doubts!
