### ISSUE TITLE
Add New Features to predictive-calc

### ISSUE THREAD

**Issue by imDarshanGK** [yashasvini121/predictive-calc#119]
Hi, I want to work on this issue as part of GirlScript Summer of Code (GSSoC). Could you please assign it to me? @yashasvini121

**Comment by MudadlaYogitha** [comment]
once review my work . I have made changes on model.py and predict.py

**Comment by imDarshanGK** [comment]
Hi @yashasvini121, I'd like to add a House Price Prediction model. The model will allow users to input house features (square footage, location, number of bedrooms, etc.) and receive a predicted price using a regression model. I'll integrate it with the existing JSON configuration system, making it easy for users to add custom data for predictions. Could you please assign this to me?

**Comment by yashasvini121** [comment]
It's already implemented in the projects

**Comment by imDarshanGK** [comment]
@yashasvini121 Could you please specify what advancements you would like to make in the predictive-calc?
