### ISSUE TITLE
Customer Income Prediction Model

### ISSUE THREAD

**Issue by deca109** [yashasvini121/predictive-calc#13]
Problem Description:

People before choosing a stream of education, making investment strategies, planning long-term savings , etc would like to know whether they would earn more or less than the average income of 50,000$ per year based on certain demographics. This model will help in classifying if the salary is high or low based on those demographics and will help the user to gather information on how the variability in the demographics can affect the salary.

Model Description:

I would use classification algorithms such as Logical Regression, Decision Trees and Random Forest as they are best for datasets that have binary prediction values. Also due to the imbalance of certain features, ensemble techniques such as bagging or boosting will have to be use to eliminate biases.

Estimated Time for Completion:

The implementation will be done within 3 days.

Expected Outcome:

Given certain socio-economic and demographic information the model will accurately classify the salary as low or high, helping users make financial decisions over a longer period of time. Predicting future income allows users to set realistic savings targets and contributions. For instance, if future income is expected to rise, they may choose to save more aggressively over time.

I would like to work on this issue under the GsSOC'24 Ext. Please assign me this issue and provide the labels.

**Comment by yashasvini121** [comment]
Sure @deca109, go ahead!

**Comment by deca109** [comment]
Hey @yashasvini121 @Pranshu-jais , I am currently facing an issue with pushing my changes to my forked repository as it says that the pickle model file exceeds the git file upload limit. It would be very helpful if someone can guide me through this (if I should add the model in gitignore or something else). Uploaded the terminal screenshot below. Also I could not figure out, where to ask for help, so I did it here. If I should do it elsewhere, I apologize for the inconvenience.

![image](https://github.com/user-attachments/assets/d2ed0b31-7fa7-49fc-bdd4-d2d25c97a968)

**Comment by Pranshu-jais** [comment]
> Hey @yashasvini121 @Pranshu-jais , I am currently facing an issue with pushing my changes to my forked repository as it says that the pickle model file exceeds the git file upload limit. It would be very helpful if someone can guide me through this (if I should add the model in gitignore or something else). Uploaded the terminal screenshot below. Also I could not figure out, where to ask for help, so I did it here. If I should do it elsewhere, I apologize for the inconvenience.
> 
> ![image](https://private-user-images.githubusercontent.com/118815246/373832388-d2ed0b31-7fa7-49fc-bdd4-d2d25c97a968.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwOTcxMDMsIm5iZiI6MTcyODA5NjgwNCwicGF0aCI6Ii8xMTg4MTUyNDYvMzczODMyMzg4LWQyZWQwYjMxLTdmYTctNDlmYy1iZGQ0LWQyZDI1Yzk3YTk2OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNVQwMjUzMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZjE4OTNjMWNlMGZjMTZkZDkzZGNmMTUwOWUxZmNmMzJjOTRlMjhlMzQzY2M0ZDYzYWViM2RlNTRmZmRlNDFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.e_4wFOgB3YfsdTm1DTrtbE9QBNiayV6xxTdPXNKeMtQ)

@deca109  you can use Git LFS  to handle large files

**Comment by deca109** [comment]
Hey @Pranshu-jais 
Sorry, I have not worked with LFS before and I can't understand what I am doing wrong here.
![image](https://github.com/user-attachments/assets/e648e69e-8068-4da8-b6fe-8120795f1f81)

**Comment by yashasvini121** [comment]
@deca109, Git LFS won't work as it's a paid feature on GitHub, and the maximum file size limit for free plans is 100MB.

So now, you can try the following approaches:
1. Use a different file format like `joblib` or `parquet` etc, and enable compression to reduce the file size.
2. Optimize your model by reducing complexity (e.g., pruning, quantization) to decrease the overall size.
3. Skip uploading the pickle file for now. You can push other files, and we'll address the model file later with an appropriate solution.
