### ISSUE TITLE
Add Sidebar for Model Selection to Improve User Navigation

### ISSUE THREAD

**Issue by KashishJuneja101003** [yashasvini121/predictive-calc#130]
🌟 **Is your feature request related to a problem?:**
Currently, the app lacks a convenient navigation tool, requiring users to scroll through the page to select different machine learning models. This impacts the user experience, especially as more models are added.

💡 **Describe the solution you'd like:**
Add a sidebar using st.sidebar.selectbox() for model selection. This would allow users to seamlessly switch between models without excessive scrolling.

🔀 **Describe alternatives considered:**
Other navigational methods such as buttons or tabs, but the sidebar is most intuitive for this use case.

📄 **Additional Context:**
A sidebar will enhance usability and overall UI consistency.

**To be Mentioned while taking the issue:**
GSSoC extd and Hacktoberfest

**Note:**
- Please review the project documentation and ensure your code aligns with the project structure.
- Please ensure that either the `predict.py` file includes a properly implemented `model_details()` function or the notebook contains this function to print a detailed model report. The model will not be accepted without this function in place, as it is essential for generating the necessary model details.
- Prefer using a new branch to resolve the issue, as it helps keep the main branch stable and makes it easier to manage and review your changes.
- Strictly use the pull request template provided in the repository to create a pull request.

**Comment by KashishJuneja101003** [comment]
Please assign this task to me.
Also, add gssoc-extd, hactoberfest and level labels.
Thank You!

**Comment by yashasvini121** [comment]
Sure @KashishJuneja101003, go ahead!
