### ISSUE TITLE
add code of conduct file 

### ISSUE THREAD

**Issue by INam1995** [yashasvini121/predictive-calc#135]
Hey @yashasvini121 

Issue: Add Code of Conduct File

I would like to request to be assigned the issue for adding a code_of_conduct.md file to this Project.
We need to create a Code of Conduct file to ensure our project fosters an open and welcoming environment. This will set guidelines for contributors on expected behavior and unacceptable conduct.

Tasks:
Create a CODE_OF_CONDUCT.md file in the root directory of the project.
Use the Contributor Covenant v1.4 as a template, ensuring that the text is tailored to our community values.
Add a placeholder email address in the enforcement section for reporting misconduct (we will update this with the correct contact details later).
Submit a pull request once completed.
Let’s ensure our project is a safe and inclusive space for everyone!

so please assign this issue to me under gssoc-ext

**Comment by yashasvini121** [comment]
Not required currently
