### ISSUE TITLE
Text Summarizing NLP Model

### ISSUE THREAD

**Issue by Peart-Guy** [yashasvini121/predictive-calc#139]
🔍 **Problem Description**:
It helps users to summarize huge texts

🧠 **Model Description**:
It will be a text summarization NLP model where user and type their huge paragraphs and the model will summarize it 

⏲️ **Estimated Time for Completion**:
Within 1 day
🎯 **Expected Outcome**:
People do face issues to summarize huge texts or students do face issues to learn huge texts. this model will help users to summarize those texts and use it according to their need, for example a learner can easily learn faster  and understand the summarized text instead of going through huge paragraphs 
📄 **Additional Context**:

**To be Mentioned while taking the issue**:
- What is your participant role? GSSOC-24 EXTD , Hactoberfest

**Note:**
- Please review the project documentation and ensure your code aligns with the project structure.
- Please ensure that either the `predict.py` file includes a properly implemented `model_details()` function or the notebook contains this function to print a detailed model report. The model will not be accepted without this function in place, as it is essential for generating the necessary model details.
- Prefer using a new branch to resolve the issue, as it helps keep the main branch stable and makes it easier to manage and review your changes.
- Strictly use the pull request template provided in the repository to create a pull request.

**Comment by yashasvini121** [comment]
Assigned @Peart-Guy

**Comment by Peart-Guy** [comment]
@yashasvini121  Kindly give the required labels like GSSOC-24 EXTD , level and Hacktober

**Comment by S-Shipra** [comment]
Can you assign this task to me pls!
