### ISSUE TITLE
Auto Update project structure section in the markdown file

### ISSUE THREAD

**Issue by yashksaini-coder** [yashasvini121/predictive-calc#146]
🌟 **Is your feature request related to a problem?**:
I can add a python file that can be used with an action workflow to automate the project-structure section

💡 **Describe the solution you'd like**:
By using python code of my own I can use it to fetch, create & update project-structure inside anywhere in the markdown file using markers, this will allow complete customization to the user where they want it to be generated. Also it is not limited to README.md only

🔀 **Describe alternatives considered**:
I have seen action workflows but they can be quite trouble to deal with, also not to mention the garbage commits they leave behind

📄 **Additional Context**:
![image](https://github.com/user-attachments/assets/0ba06daf-7544-45e6-9e34-8c4d8f9dffe8)

**To be Mentioned while taking the issue**:
- What is your participant role?  
- GSSOC'24

**Note:**
- Please review the project documentation and ensure your code aligns with the project structure.
- Please ensure that either the `predict.py` file includes a properly implemented `model_details()` function or the notebook contains this function to print a detailed model report. The model will not be accepted without this function in place, as it is essential for generating the necessary model details.
- Prefer using a new branch to resolve the issue, as it helps keep the main branch stable and makes it easier to manage and review your changes.
- Strictly use the pull request template provided in the repository to create a pull request.

**Comment by yashksaini-coder** [comment]
@yashasvini121 Review the issue and assign it to me, with proper labels of both `hacktoberfest` & `gssoc`

**Comment by yashasvini121** [comment]
Nice idea, but it's not required right now
