### ISSUE TITLE
Add new model # Heart Disease Predictor

### ISSUE THREAD

**Issue by cyberfantics** [yashasvini121/predictive-calc#148]
🔍 **Problem Description**:  
The Heart Disease Predictor aims to address the rising concerns regarding heart disease, one of the leading causes of mortality worldwide. Predicting the likelihood of heart disease based on patient data, such as age, cholesterol levels, blood pressure, and other health indicators, can enable early detection and prevention. This solution can assist healthcare professionals in making informed decisions, ultimately improving patient outcomes.

🧠 **Model Description**:  
The model will use a machine learning approach, such as Logistic Regression, Decision Trees, or a Neural Network, to classify patients as at risk or not at risk for heart disease. The chosen algorithm will be tuned to achieve high accuracy while balancing sensitivity (recall) and specificity. The model will be trained using a heart disease dataset that contains various health metrics. Features will be selected and preprocessed based on their significance in predicting heart disease.

⏲️ **Estimated Time for Completion**:  
The estimated time to fully implement and test the model is **2 days**. This timeframe includes:
- Data collection and preprocessing: 1 day
- Model training, testing, and deployment: 1 day

🎯 **Expected Outcome**:  
The expected outcome is a robust machine learning model capable of predicting the risk of heart disease with a high level of accuracy. The model should enhance the decision-making process for healthcare providers and support preventative measures for patients. Additionally, it will include a `model_details()` function to generate a comprehensive report on model performance and key metrics.

📄 **Additional Context**:  
The project will utilize open-source heart disease datasets such as the Cleveland Heart Disease dataset from the UCI Machine Learning Repository. Relevant health indicators (features) include age, gender, cholesterol level, blood pressure, fasting blood sugar, electrocardiographic results, etc. Data preprocessing steps like normalization, feature scaling, and handling missing values will be performed as needed.

---

**To be Mentioned while taking the issue**:
GSSOC
---

**Note**:
- Please review the project documentation and ensure your code aligns with the project structure.
- Ensure that either the `predict.py` file includes a properly implemented `model_details()` function or the notebook contains this function to print a detailed model report. The model will not be accepted without this function in place, as it is essential for generating the necessary model details.
- Prefer using a new branch to resolve the issue, as it helps keep the main branch stable and makes it easier to manage and review your changes.
- Strictly use the pull request template provided in the repository to create a pull request.

**Comment by yashasvini121** [comment]
A similar issue already exists
