### ISSUE TITLE
📝 Morse Code Translator 

### ISSUE THREAD

**Issue by Anushka-Pote** [yashasvini121/predictive-calc#169]
📝 Morse Code Translator 
🔍 Problem Description: The goal of this project is to create a Morse code translator that allows users to input text and receive the corresponding Morse code output. This functionality is essential for users interested in learning Morse code, communicating using Morse code, or integrating it into other applications. By providing a user-friendly interface for translation, we enhance accessibility to this classic communication method.

🧠 Model Description: The Morse code translator will use a straightforward dictionary-based approach to map each letter and digit to its Morse code equivalent. The implementation will involve:
A Python dictionary that contains the mappings for each character to Morse code.
A function to convert user-input text into Morse code by looking up each character in the dictionary. This approach is efficient for the problem, as it allows for quick lookups and straightforward implementation.

⏲️ Estimated Time for Completion: Approximately 2-4 hours to implement, test, and refine the translation functionality, along with user interface elements in the Streamlit application.

🎯 Expected Outcome: Upon completion, users will be able to input any text string and receive the corresponding Morse code translation. This feature will enhance the application's functionality by providing a unique and educational tool for users. The implementation will improve user engagement and promote interest in Morse code.

📄 Additional Context: The translator will be implemented using Streamlit, allowing for an interactive web application experience. The project will be structured to ensure clear code organization, with appropriate error handling and user prompts.

**To be Mentioned while taking the issue**:
- What is your participant role? - GSSOC-EXT and Hacktoberfest24

**Note:**
- Please review the project documentation and ensure your code aligns with the project structure.
- Please ensure that either the `predict.py` file includes a properly implemented `model_details()` function or the notebook contains this function to print a detailed model report. The model will not be accepted without this function in place, as it is essential for generating the necessary model details.
- Prefer using a new branch to resolve the issue, as it helps keep the main branch stable and makes it easier to manage and review your changes.
- Strictly use the pull request template provided in the repository to create a pull request.

**Comment by aaryak1369** [comment]
I'd like to work on this issue.
Participant Role: Hacktoberfest 2024

**Comment by aaryak1369** [comment]
**Doubt**
since the morse code translator doesnt involve any machine learning models (its purely a text-to-morse mapping), i dont need to add anything related to machine learning inside the models/ folder, right?

**Comment by Anushka-Pote** [comment]
Actually we have to ask the author about the details on how they want it to happen, @yashasvini121 will check the issue and assign it. I just raised an issue for wanting to work on this morse code translator.

**Comment by yashasvini121** [comment]
Hey, I believe your Morse Code Translator idea doesn’t use any ML Model. If it does involve AI/ML, please let me know, as this project is focused exclusively on ML prediction models. I am closing this issue for now.
