### ISSUE TITLE
Update Project Structure.md and Tutorial.md

### ISSUE THREAD

**Issue by yashasvini121** [yashasvini121/predictive-calc#174]
🌟 **Problem**:  
  
1. The `project-structure.md` file doesn't include descriptions for new files added to the project, such as `dev-requirements` and `docker-compose`.  
2. Contributors do not update the `requirements.txt` file properly.  

💡 **Expected Solution**:  
  
1. Add a step in `tutorial.md` instructing contributors to update the `requirements.txt` file when necessary and test the entire project to ensure there are no version conflicts between packages.  
2. Update `project-structure.md` by including descriptions for the missing files.  

**Approach**:
1. Fork the repo
2. Create a new branch and name it like `fix-docs`
3. Clone the repo locally, or you can even change the files on github.dev, for this, change your repo url from `github.com/<username>/<repo>` to `github.dev/<username>/<repo>`
4. Commit the changes
5. Make a pr for it and link this issue

**Note:**
- Prefer using a new branch to resolve the issue, as it helps keep the main branch stable and makes it easier to manage and review your changes.
- Strictly use the pull request template provided in the repository to create a pull request.

**Comment by yashasvini121** [comment]
Hey @Xblade9669, let me know if you'd like to work on this issue. Feel free to reach out if you have any questions or need any clarification.

**Comment by prachi-0319** [comment]
Hey, I would like to take up this open issue!
I have prior experience in technical documentation and structuring the projects. I can make a valuable contribution to this project and make sure the Project Structure.md and Tutorial.md give clear instructions for the contributors.

**Comment by prachi-0319** [comment]
Hi, thank you so much for assigning me this issue!
Just one doubt, in the models folder there are a lot of directories and subdirectories, a directory for each project specifically. Do allow of those need to be added in the directory layout on project-structure along with descriptions?

**Comment by yashasvini121** [comment]
No, don't list each model individually. Only include files that are not in the root directory, such as `docker-compose.yml`. Additionally, move `machine-learning.gif` to the `assets/images` folder. And include it in project structure as well.
