### ISSUE TITLE
[Documentation] Add Table to Display Repository Statistics in README.md 

### ISSUE THREAD

**Issue by REHAN-18** [yashasvini121/predictive-calc#183]
🌟 **Is your feature request related to a problem?**:
The issue involves adding a well structured table to display repository statistics, such as the number of stars, forks, issues, and pull requests, directly in the README.md file. This will help contributors and users track the activity and contributions at a glance.

💡 **Describe the solution you'd like**:
###Steps to Implement:
Create a table in the README.md file displaying the following repository statistics:
1-Stars
2-Forks
3-Open Issues
4-Open Pull Requests
5-Closed Pull Requests
### Use markdown syntax to include badges or icons for each statistic.
Add dynamic links to the corresponding sections of the repository for easy access (e.g., link to the "Issues" or "Pull Requests" tabs).
<img width="779" alt="Screenshot 2024-10-26 at 12 09 59 AM" src="https://github.com/user-attachments/assets/2aafb463-5f4e-46ce-a33a-d7206ba66da3">

### also I want to add this its enhance the readme & I use markdown to implement this 
<img width="847" alt="Screenshot 2024-10-26 at 12 23 23 AM" src="https://github.com/user-attachments/assets/bb200677-9f4d-4dc3-a2cf-a9f619f52d0a">

**To be Mentioned while taking the issue**:
- What is your participant role? 
- GSSOC, Hacktoberfest

**Comment by yashasvini121** [comment]
This issue isn't needed at the moment. Please review the existing issues or open a new one, relevant to the project and AI/ML if necessary.
