### ISSUE TITLE
Add Github Greeting Bot

### ISSUE THREAD

**Issue by KiranBaliga** [yashasvini121/predictive-calc#19]
Hey 🥳 Looks like an amazing project idea! I see this repo lacks a small enhancement Github Greetings bot that sends auto messages to greet new users when they raise a PR or an issue. Let me know if you would like this level1 set up! Please assign to me if interested! (GSSoC24-Ext Contribution)

**Comment by yashasvini121** [comment]
Thank you for the suggestion. But, we don't require the GitHub Greetings bot for this project at the moment.
