### ISSUE TITLE
Adde Code Of Conduct 

### ISSUE THREAD

**Issue by Dipanita45** [yashasvini121/predictive-calc#199]
quest.

**Comment by Dipanita45** [comment]
Please assign me this issue 
@yashasvini121

**Comment by Dipanita45** [comment]
Please assign me this issue 
@yashasvini121

**Comment by Dipanita45** [comment]
Please assign me this issue 
@yashasvini121

**Comment by yashasvini121** [comment]
This issue isn't needed at the moment. Please review the existing issues or open a new one, relevant to the project and AI/ML if necessary.
