### ISSUE TITLE
Add Fraudulent Transaction Detection Model to the Project

### ISSUE THREAD

**Issue by yashasvini121** [yashasvini121/predictive-calc#2]
We need to add new models to the project to enhance its capabilities. Please follow the tutorial in the link below for step-by-step guidance on how to properly implement and integrate new models:

[Tutorial: How to Add New Models](https://github.com/yashasvini121/predictive-calc/blob/master/docs/tutorial.md)

Tasks:

Review the provided tutorial.
Add new models as per the instructions.
Ensure that all new models are properly integrated with existing functionality.
Update any necessary documentation or comments.

**Comment by DG492003** [comment]
hi @yashasvini121 I would like to contribute in this issue under gssoc'24. I will add new model for fradulent transaction detection.

**Comment by yashasvini121** [comment]
Sure, go ahead👍

**Comment by priyans877** [comment]
Hi @yashasvini121 I would like to contribute in this issue also , can i also work on that under Gssoc 24 Ext.

**Comment by JahnaviDhanaSri** [comment]
Hi @yashasvini121,

I would like to take on the task of adding new models to the project as described in issue #4. Expanding the project's functionality by integrating new models is an exciting opportunity, and I'm eager to contribute!

Here's my plan for tackling this issue:

Review the Tutorial: I will thoroughly review the provided tutorial on adding and integrating new models to ensure I follow the recommended practices.
Implementation: I will implement the new models as per the tutorial's guidelines, ensuring they align with the project's existing framework.
Integration: I will focus on integrating these models seamlessly with the current project features, ensuring they work well together.
Documentation: I will update the relevant documentation and add comments to clarify the implementation process for future maintenance.

Could you please assign this issue to me

**Comment by yashasvini121** [comment]
@DG492003 updates?

**Comment by DG492003** [comment]
[#113 ](url)
