### ISSUE TITLE
Fake news detection model

### ISSUE THREAD

**Issue by Dharun235** [yashasvini121/predictive-calc#202]
🔍 **Problem Description**:  
The **Fake News Detection** project addresses the growing concern over misinformation online, which can have significant social, political, and economic consequences. This model will classify news articles as either "fake" or "real," helping users quickly determine the credibility of a news source. By automating the detection process, we aim to reduce the spread of false information and promote reliable news consumption.

🧠 **Model Description**:  
The model utilizes a **Naive Bayes Classifier** for binary text classification, a probabilistic approach ideal for handling high-dimensional text data. To preprocess the text, **TF-IDF (Term Frequency-Inverse Document Frequency)** is used, which transforms the textual data into numerical form by giving weight to words based on their importance in each document. Naive Bayes is particularly effective for this task due to its simplicity and effectiveness in text classification, making it suitable for detecting fake news with high accuracy and low computational cost.

⏲️ **Estimated Time for Completion**:  
The project is expected to take approximately **2 days**, which includes data preprocessing, model training, evaluation, and documentation.

🎯 **Expected Outcome**:  
Upon completion, the model will be able to classify news articles with a target accuracy of around **85%**, along with strong precision, recall, and F1-score metrics for each class. The solution will allow users to input news articles and quickly obtain a classification that indicates whether the content is likely to be fake or real, providing a valuable tool for both individuals and organizations to assess news credibility.

📄 **Additional Context**:  
This project uses a well-known dataset from Kaggle, the Fake and Real News Dataset. It is structured as a basic machine learning project and can be enhanced in future iterations by exploring different classification algorithms or using deep learning approaches for better accuracy. This initial implementation prioritizes simplicity, efficiency, and interpretability for ease of understanding and deployment.

**To be Mentioned while taking the issue**:
- What is your participant role? (e.g., Hacktoberfest, GSSOC, SSOC, etc.)
- Contributor under Hacktoberfest and GSSoC'Extd

**Note**:
- Review the project documentation and align the code with the existing structure.
- Ensure that either the `predict.py` file or the notebook includes a `model_details()` function that provides a detailed model report. This function is essential for generating an overview of model metrics and will be required for acceptance.
- Use a separate branch to manage changes, maintaining stability in the main branch.
- Follow the repository's pull request template for creating and submitting a pull request.

**Comment by yashasvini121** [comment]
These models are not needed at the moment because TensorFlow or CNN makes the Streamlit app too heavy, impacting performance.

**Comment by yashasvini121** [comment]
If you have any non-TensorFlow NLP projects, feel free to create an issue for them.
