### ISSUE TITLE
Want to add security policy 

### ISSUE THREAD

**Issue by Dipanita45** [yashasvini121/predictive-calc#203]
🌟 **Is your feature request related to a problem?**:
<Want to add the security policy to protect the website against the harms 

💡 **Describe the solution you'd like**:
<!-- Add security policy >

Please assign me the issue

**Comment by Dipanita45** [comment]
Please assign me this issue 
@yashasvini121

**Comment by yashasvini121** [comment]
This issue isn't needed at the moment. Please review the existing issues or open a new one, relevant to the project and AI/ML if necessary.
