### ISSUE TITLE
Adding Parkinson's Disease Detection System to Streamlit Application

### ISSUE THREAD

**Issue by sanyadureja** [yashasvini121/predictive-calc#22]
Problem Description:
The current Streamlit application lacks a health-focused tool. Adding a Parkinson's Disease Detection System will allow users to assess the likelihood of having Parkinson's based on 22 input features derived from voice data, addressing the need for accessible early detection tools.

Model Description:
The model will utilize an XGBoost Classifier trained on the UCI Parkinson's Disease Dataset. It will preprocess data using MinMaxScaler to normalize the 22 features. XGBoost is chosen for its high accuracy in classification tasks.

Estimated Time for Completion:
5-7 days for integration, testing, and optimization.

Expected Outcome:
A functional Parkinson's Disease detection calculator within the Streamlit app, allowing users to input values for the 22 features and receive predictions, thereby enhancing the application's health-related functionality.

Additional Context:
The feature will be added as the third calculator in the existing Streamlit application, utilizing the UCI Parkinson's dataset. I will first explore the current approach to feature input and later aim to implement a better method for handling input values.

Dataset:
https://archive.ics.uci.edu/dataset/174/parkinsons

Reference Repository:
https://github.com/sanyadureja/Parkinson-Disease-Detection

**Comment by sanyadureja** [comment]
@yashasvini121 If you find this idea suitable, please assign it to me as part of GSSoC'24 Extended. Looking forward to your response.

Thank you!

**Comment by yashasvini121** [comment]
Sure, go ahead, @sanyadureja!

**Comment by sanyadureja** [comment]
okay thank you @yashasvini121.
