### ISSUE TITLE
Stress Level detection

### ISSUE THREAD

**Issue by SimranShaikh20** [yashasvini121/predictive-calc#220]
🔍 **Problem Description**:
This project will help to know about mental health of any body becoz in todays era many of person have lots of stress  for while working in job  , or etc 

🧠 **Model Description**:
sklearn , eda , data cleaning , data processsing 

⏲️ **Estimated Time for Completion**:
today 

**To be Mentioned while taking the issue**:
- What is your participant role? GSSOC 24 Extd

@yashasvini121 pls assign me this issue as this is important topic based on today's  era !

**Comment by SimranShaikh20** [comment]
@yashasvini121 !

**Comment by SimranShaikh20** [comment]
@yashasvini121 pls assign me this issue I want to work on it!

**Comment by yashasvini121** [comment]
This model already exists in the project
