### ISSUE TITLE
Add Decision tree classifier model to categorize houses into price ranges

### ISSUE THREAD

**Issue by trishap-16** [yashasvini121/predictive-calc#23]
Problem Description:

The lack of categorical insights into house prices, limited ability to capture complex feature interactions, and reduced interpretability for non-technical stakeholders. The existing linear regression model may not effectively highlight significant features, risk overfitting, or accommodate varying market behaviors, ultimately hindering accurate predictions and data-driven decision-making.

Model Description:

A Decision Tree Classifier is a supervised learning algorithm that uses a tree-like structure to classify data. It splits datasets based on feature values, enabling clear, interpretable decisions. In the project, it categorizes house prices, identifies influential features, and complements regression models for a comprehensive analysis of housing data.

Estimated Time for Completion:

I can implement the model within 2- 3 days.

Expected Outcome:

This enables effective categorization of house prices into distinct segments, enhance interpretability of decision-making processes, identify key influential features, and improve prediction accuracy. 

Additional Context:

I could work on this if you assign me to this issue along with gssoc-ext, hacktoberfest-accepted, level2 labels

**Comment by yashasvini121** [comment]
Sure @trishap-16, the `level` label will be added after you submit your PR.

We already have a house price prediction page, but since you're using a different model, please create a new folder named models/house_price_decision_tree_classifier for now. We can explore a better structure later on.
