### ISSUE TITLE
Customer Churn Prediction

### ISSUE THREAD

**Issue by Stuti333** [yashasvini121/predictive-calc#24]
Problem Description:
Predict customer churn to help businesses retain customers and reduce revenue loss.

Model Description:
Logistic Regression or Random Forest Classifier. These models are suitable for binary classification problems and can provide feature importance insights.

Estimated Time for Completion:
3-4 days, including data preparation, model implementation, and integration with the Predictive Calc project.

Expected Outcome:
Allowing businesses to identify customers at risk of churning with a high degree of accuracy. Users will be able to input key customer features , receiving immediate predictions on the likelihood of churn. This model will not only provide binary predictions but also offer insights into the most influential factors contributing to churn, enabling businesses to take targeted retention actions.

Kindly assign me this issue

**Comment by yashasvini121** [comment]
Assigned @Stuti333

**Comment by yashasvini121** [comment]
Updates @Stuti333?

**Comment by Stuti333** [comment]
I have made the required changes and updated the files and created a nèw PR #80
