### ISSUE TITLE
[New Model] Mental Stress Level Detection

### ISSUE THREAD

**Issue by J-B-Mugundh** [yashasvini121/predictive-calc#25]
Problem Description:

The increasing use of social media has been linked to rising mental stress levels, particularly due to behaviors such as constant comparison with others, seeking validation, and frequent distractions. This project aims to detect the mental stress level of individuals caused by social media usage by analyzing specific behavioral patterns and emotional states. By identifying key factors such as frequency of use without purpose, feelings of worry, difficulty concentrating, and sleep issues, we can create a model to assess and predict stress levels.

Model Description:

The stress detection model will be built using a Random Forest algorithm, a robust and versatile machine learning technique known for its accuracy and ability to handle complex datasets. The model will take various behavioral and emotional indicators as input features to  predict the mental stress level of the user based on their social media habits.

Estimated Time for Completion:

The estimated time for building, training, and validating the Random Forest model is approximately 2-3 days. This includes data collection and preprocessing, model training, and performance evaluation, followed by any necessary fine-tuning of the model.

Expected Outcome:

The expected outcome of this project is a reliable machine learning model capable of detecting an individual's mental stress level due to social media usage. The model will provide insights into the extent of stress users may be experiencing, allowing for better understanding and potential intervention to mitigate the negative psychological effects of social media.

**Comment by J-B-Mugundh** [comment]
@yashasvini121 Please assign me this issue with gssoc-extd and hacktoberfest labels.

**Comment by yashasvini121** [comment]
Sure, @J-B-Mugundh, go ahead!

**Comment by J-B-Mugundh** [comment]
@yashasvini121 Could you please add label here please!
