### ISSUE TITLE
Enhancing House Predictor Model

### ISSUE THREAD

**Issue by ChitteshKumar** [yashasvini121/predictive-calc#30]
Problem Description:

The current house price prediction model achieves 68% accuracy, which is suboptimal for this regression task. The model relies on a standard multiple linear regression approach and lacks regularization or advanced techniques to capture more complex relationships in the data.

Model Description:

The current model is based on linear regression, which may suffer from overfitting or underfitting, especially in the presence of high-dimensional or irrelevant features. The performance can be improved by incorporating regularization techniques, feature engineering, and more robust machine learning models.

I propose the following improvements to enhance model performance:

- Hybrid Regularization: Using both L1 and L2, helps reduce overfitting and better feature selection, improving model accuracy by focusing on significant predictors.
- Ensemble Learning: Utilizing ensemble techniques such as Random Forest can capture complex patterns and interactions between features, which linear models may overlook.

Estimated Time for Completion: I estimate that it will take around 5-7 days to implement these improvements.

Expected Outcome: With these enhancements, I expect to see an improvement in the model’s accuracy from 68% to a more competitive level. 

@yashasvini121, I would love to contribute to this issue under gssoc24-extd.

Thank you for your consideration.

**Comment by yashasvini121** [comment]
Sure, @ChitteshKumar, go ahead! 

However, please make sure to go through the project structure in the docs and include the dataset and notebook if relevant to the project.

**Comment by ChitteshKumar** [comment]
Yeah sure, I'll do that. Just to inform, I am working on this issue. I am trying to use different methods to improve the model.

**Comment by ChitteshKumar** [comment]
Just to inform I have working on this will be done by Sunday, 20th Oct

**Comment by ChitteshKumar** [comment]
Hi @yashasvini121 i have completed this issue can you please check and merge it.

**Comment by ChitteshKumar** [comment]
Hi @yashasvini121  pls look at this
