### ISSUE TITLE
Enhancement : Improve the 'APP' Page

### ISSUE THREAD

**Issue by akarshghildyal** [yashasvini121/predictive-calc#43]
# Title : Enhance APP page
## Objective : To improve the main page by making it a bit more descriptive, adding a couple of stock images and explaining the entire project properly. 
![image](https://github.com/user-attachments/assets/4b3b8456-430a-4872-82b9-116543fb99c2)

## Proposed Page Structure:

The page could look like:
![image](https://github.com/user-attachments/assets/268d263c-b882-4131-932b-f0114d43568a)
 
 ---
 
 ### Kindly assign this to me and add hacktoberfest related tags. Thank you.

**Comment by yashasvini121** [comment]
Sure, @akarshghildyal, go ahead!
