### ISSUE TITLE
Error Handling for External Modules

### ISSUE THREAD

**Issue by KashishJuneja101003** [yashasvini121/predictive-calc#44]
**Bug Description:**
The program dynamically loads external modules (like model functions) using importlib.util. However, if:
1. The module file path (model_predict_file_path) is incorrect or the file is missing.
2. The specified function (get_prediction) does not exist in the loaded module.
3. The module file has errors (syntax or runtime errors).
It results in the app crashing instead of handling the error gracefully.

**To Reproduce:**
1. Provide an incorrect or non-existent path for model_predict_file_path in the JSON configuration.
2. Ensure the get_prediction function is missing in the specified module file.
3. Introduce an error (like a syntax error) in the module file.

**Expected Behavior:**
Instead of crashing or throwing an unhandled exception:
1. The app should catch errors related to missing modules or functions.
2. Display an appropriate error message to the user, such as:
- "Error loading model file: File not found."
- "Error: Model prediction function get_prediction not found."
- "Error in model file: Syntax error."

**Comment by KashishJuneja101003** [comment]
Kindly assign this to me and add hacktoberfest and gssoc-extdrelated tags. Thank you.

**Comment by yashasvini121** [comment]
Sure, @KashishJuneja101003, go ahead!

**Comment by KashishJuneja101003** [comment]
Please assign the level.
