### ISSUE TITLE
Implement Docker Containerization for the Project

### ISSUE THREAD

**Issue by RandomSummer** [yashasvini121/predictive-calc#45]
I can enhance the UI/UX design, and add features such as the user will be aware of which ML model they are using beforehand, and also add the feature "the graphical report of the provided data". I can even add the use of docker to containerize the whole project which can eventually help the developer and operator simultaneously. 

By incorporating this we can do this project on any system regardless of which OS kernel it is used.

I will be sharing a screenshot of my previous project for you to look over.

If you like my idea, kindly let me know.

**Comment by yashasvini121** [comment]
For now, please focus on the containerization task, as the UI/UX issues are being handled by other contributors.
Make sure to include ` setup.sh` and `setup.ps1` files.

@RandomSummer assigned!

Also mention estimated time you need for this task.

**Comment by RandomSummer** [comment]
I have completed all my analysis and operation. Now submitting the proposed blueprint for the Docker Architecture, to make things work needs your app's blueprint for routing and networking purposes.

![Screenshot 2024-10-08 092135](https://github.com/user-attachments/assets/5e0dab8f-3097-403f-a9fd-e30248dd712d)

Few bugs:
->  To successfully run the App. python version should be specified (Python 3.11) as (Python 3.12 and 3.13 doesn't support a few features yet like ydata-profiling etc)

Suggestions:
-> I would like a specific OS kernel in Docker that the users won't need to download, it will run automatically.
-> Just download and run the image, and everything will be fine.

**Comment by yashasvini121** [comment]
This project does not utilize a database, and there's no need to complicate matters by maintaining separate models. Instead, please create a straightforward Docker Compose file that handles the pip installations and subsequently runs the project.

Additionally, update the README file to include instructions on how to run the project using Docker
