### ISSUE TITLE
Nav Bar and UI components are missing

### ISSUE THREAD

**Issue by NishantRana07** [yashasvini121/predictive-calc#51]
**Is your feature request related to a problem? Please describe.**
There is no top navbar that provides info about Project also No Logo

I can implement UI in it from Nav to footer

@yashasvini121 LMK if you need any feature and assign it to me under GSSoC and Hacktoberfest

**Comment by yashasvini121** [comment]
@NishantRana07, Currently, some contributors are working on ui/ux so you can check out other issues.
