### ISSUE TITLE
Add Problem and Model Descriptions to Pages

### ISSUE THREAD

**Issue by yashasvini121** [yashasvini121/predictive-calc#54]
Currently, the pages in our application do not include problem descriptions or model descriptions. To improve clarity and understanding for users, we need to add these descriptions to the `Model Details` tab of each page.

### Task Overview:

1. **Update `pages/pages.json`:**
   - For each page, write a clear problem statement and a model description.
   - Maintain the existing structure of the `pages.json` file while adding the new fields.

   **Example Structure:**
   ```json
   {
     "House Price Estimator": {
       "title": "House Price Estimator",
        .......
       "tabs": [
         {
           "name": "Estimator",
           "type": "form",
           "form_name": "House Price Form"
         },
         {
           "name": "Model Details",
           "type": "model_details",
           "problem_statement": "The model predicts the house prices based on the given input features.",
           "description": "This model uses Linear Regression to predict the house prices."
         }
       ]
     }
        .......
   }
   ```

2. **Update Relevant Classes:**
   - Modify the `page_handler` class and any other relevant components to ensure that the problem statement and model descriptions are displayed at the top of the `Model Details` tab.

### Acceptance Criteria:

- Each page in the `pages/pages.json` file must have a corresponding problem statement and model description under the `Model Details` tab.
- The `Model Details` tab should display these descriptions prominently at the top.
- Ensure that these updates do not disrupt any existing functionality.

### Additional Notes:

- Follow the current formatting or use a similar one and structure used in the `pages.json` file.
- After implementation, please test the changes to verify that the new descriptions are displayed correctly without causing any issues.
- Provide a screenshot in the pr

*Mention estimated time you require for this task*

**Comment by Namit2111** [comment]
HI! can i get assigned for this

**Comment by yashasvini121** [comment]
Mention estimated time you require for this task ??

**Comment by Namit2111** [comment]
2 - 3 days

**Comment by yashasvini121** [comment]
Sure, @Namit2111, go ahead!

**Comment by Namit2111** [comment]
Hey @yashasvini121 you have nor merged my PR yet! Is there any issues that needs to be addressed in that PR?
