### ISSUE TITLE
Add contributors in readme.md 

### ISSUE THREAD

**Issue by sakshamsaraf23** [yashasvini121/predictive-calc#56]
It lacks Contributors Profiles in Readme.md

It should be Like the image that I have shared

Hey! @yashasvini121 can you assign me this issue under GSSoC-Extd and Hacktoberfest so that I can raise a PR.
![373815323-76171289-5b05-48c4-a5be-dc8ac76d70cb](https://github.com/user-attachments/assets/2deb438e-fee0-4e4d-8c0f-85c6cf490039)

I will add this type of Live Contributor Profile Photos in it

**Comment by yashasvini121** [comment]
Sure, @sakshamsaraf23, go ahead!

**Comment by yashasvini121** [comment]
Hi @sakshamsaraf23,

I noticed that the contributors' profile you added is currently static and does not update the list dynamically. Please implement a dynamic approach instead? So that the contributor information stays up-to-date and reflects changes automatically.

**Comment by sakshamsaraf23** [comment]
I m sorry for the inconvenience sir but it is a dynamic approach and sometimes it takes a little bit of extra time to update the list depending upon the load the API is handling currently. Just for few more hours if it's still not visible i will manually change it.

**Comment by yashasvini121** [comment]
Based on my research, this issue can only be resolved by manually updating the `README.md` or by using github actions. You don’t need to worry about it; I believe it would be better if I make the changes once we have some more contributors. If that's not the case, then let me know.

**Comment by sakshamsaraf23** [comment]
Ok sir I'll look into it
