### ISSUE TITLE
No Pull Request Template in repository

### ISSUE THREAD

**Issue by AHSANATIQ98** [yashasvini121/predictive-calc#59]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
There should be PR template in .github folder it would by better

**Describe alternatives you've considered**

**Additional context**

**Comment by yashasvini121** [comment]
Sure, @AHSANATIQ98, go ahead! Please also include an **estimated time** to resolve this issue. Are you a contributor under GSSOC- extended?

Make sure the PR template includes the following:

1. A reference to the issue being resolved (e.g., "This PR resolves #<issue-number>").
2. A description of your modifications.
3. Screenshots or videos demonstrating the implemented solution if any.
4. Confirmation that your new code aligns with the current [project structure](https://github.com/yashasvini121/predictive-calc/blob/master/docs/project-structure.md).
5. Any additional details.

**Comment by AHSANATIQ98** [comment]
Sure!

**Comment by yashasvini121** [comment]
@AHSANATIQ98, Please complete this issue by today.

**Comment by AHSANATIQ98** [comment]
can you add label of gsso-ext
