### ISSUE TITLE
Issue: Implement Logging for Model Training and Predictions

### ISSUE THREAD

**Issue by vibhorjoshi** [yashasvini121/predictive-calc#6]
The code lacks a logging mechanism to track important events, such as when the model is trained, saved, or when a prediction is made. Logging would help in debugging and monitoring model performance.

Suggested Changes:

Add logging to track when models are saved or loaded.
Log model training details, such as RMSE or other performance metrics.
Log prediction inputs and outputs for traceability.

**Comment by yashasvini121** [comment]
Sure, @vibhorjoshi, go ahead!

**Comment by vibhorjoshi** [comment]
@yashasvini121 but I given a mentor role

**Comment by yashasvini121** [comment]
@vibhorjoshi, If you're a mentor in GSSOC Extended, you can either work on this personally without it counting toward program contributions or leave the issue for others. However, when creating future issues, do mention your role in the program (if any) beforehand.
