### ISSUE TITLE
feat : contibutors page 

### ISSUE THREAD

**Issue by akarshghildyal** [yashasvini121/predictive-calc#67]
**Describe the solution you'd like**
A dedicated page for contributors with their github profile pictures and number of commits.

**How?**
- create cards
- use github api
- fetch data
- fill in cards

**Additional context**
![image](https://github.com/user-attachments/assets/a1eca72d-6d5e-4f69-9513-351d83a23495)

---

### Kindly mark with relevant labels for hacktoberfest. Thank you.

**Comment by yashasvini121** [comment]
This feature isn't needed at the moment, as a similar 'thank contributors' section has already been added to the readme.

**Comment by akarshghildyal** [comment]
@yashasvini121 hello, in the 'new issue' template, the text under the headings (e.g., Is your feature request related to a problem?) is written directly instead of being commented out. To keep the template clean, it might be better if those instructions were commented, so they don't appear in the actual issue submission.

For example, instead of:
**Describe the solution you'd like**
A clear and concise description of what you want to happen.

It could be:
**Describe the solution you'd like**
```<!-- A clear and concise description of what you want to happen. -->```

just a small fix, this would avoid prevent accidental editing.
