### ISSUE TITLE
[New Model] Gold Price Prediction

### ISSUE THREAD

**Issue by J-B-Mugundh** [yashasvini121/predictive-calc#72]
### Problem Description:
The gold price is influenced by a variety of economic factors, including stock market performance, crude oil prices, silver prices, and currency exchange rates. Predicting gold prices has become increasingly important for investors and financial analysts looking to make informed decisions in the commodities market. This project aims to build a machine learning model that can predict gold prices using key financial indicators such as the S&P 500 index (SPX), crude oil prices (USO), silver prices (SLV), and the EUR/USD exchange rate.

By analyzing these factors, we can gain valuable insights into how fluctuations in these markets influence gold prices, allowing for more accurate forecasting.

### Model Description:
The gold price prediction model will be built using Linear Regression. The model will take historical data from financial indicators (SPX, USO, SLV, EUR/USD) as input features to predict future gold prices (GLD). The chosen model is well-suited for capturing the relationships between these financial variables and gold prices, enabling accurate forecasting.

### Estimated Time for Completion:
The project is expected to take approximately 2-3 days to complete. This includes the following steps:

- Data Collection & Preprocessing: Loading the gold price dataset, handling missing values, and normalizing the data.
- Model Training & Validation: Training the Random Forest model, validating its performance, and fine-tuning the model for optimal accuracy.
- Model Evaluation: Assessing the model’s performance using metrics like Mean Squared Error (MSE) and R-squared score.

### Expected Outcome:
The outcome of this project will be a machine learning model capable of accurately predicting gold prices based on key economic indicators. The model will help financial analysts and investors forecast gold price trends and make informed decisions, improving their ability to hedge risks and seize market opportunities. Additionally, the model's insights into how different financial factors interact with gold prices will enhance our understanding of the gold market's behavior.

**Comment by J-B-Mugundh** [comment]
@yashasvini121 I'm a gssoc-extd contributor and I would like to contribute on this issue!

**Comment by yashasvini121** [comment]
Sure, @J-B-Mugundh, go ahead!

The final result should include both a model and a form to interact with it.

**Comment by J-B-Mugundh** [comment]
@yashasvini121 Could you please add the level label please!
