### ISSUE TITLE
A fire detection model

### ISSUE THREAD

**Issue by Vishisht16** [yashasvini121/predictive-calc#75]
Problem Description:

A real-time model that detects fire in an image which can be useful to generate alarms or send warnings based on that.

Model Description:

I'll be using a computer vision based cascade model to identify fires. This model will be able to integrate with camera and threading will help in running it in backend.
I'll also add an alarm to be rung when fire breaks out and also send an email signal to a recipient.

Descriptive document: [README.md](https://github.com/user-attachments/files/17268824/README.md)

Estimated Time for Completion: within 24-36 hours **after** assignment

Expected Outcome: 

This model will not just be a static model for prediction. It will be a practically applicable and useful one.

**Comment by yashasvini121** [comment]
Sure, @Vishisht16, go ahead!
I assume that the end result is a form where users can upload an image, and the model will determine whether the image contains fire or represents a potential fire hazard.

**Comment by Vishisht16** [comment]
No, that's a basic model
The end result is supposed to integrate with a computer webcam or a CCTV camera to ring an alarm upon fire detection 
It will be a code continuously running in backend and monitoring the video
It will also send an email report to a designated recipient 

Also, you haven't assigned a level yet
So I request you to do that depending on the information I've provided you
It should likely be a level 3 project but I'll leave that to your judgement
