### ISSUE TITLE
Enhance Issue Templates

### ISSUE THREAD

**Issue by yashasvini121** [yashasvini121/predictive-calc#78]
Please enhance all the issue templates by incorporating the following points, where they seem to be suitable:

1. **Description:** Provide a clear and concise description of the issue or feature being reported.

2. **Current Scenario / Bugs:** Detail the current scenario or any bugs present, including steps to reproduce if applicable.

3. **Additional Details:** Include any additional information that may be relevant to understanding the issue or feature request.

4. **Time Estimate:** Add a field for contributors to estimate the time needed to resolve the issue.

5. **Hacktoberfest Submission Checkbox:** Include a checkbox to indicate if the contribution is being made under Hacktoberfest.

6. **GSSOC Extended Submission Checkbox:** Include a checkbox to indicate if the contribution is being made under GSSOC Extended.

**Note:**
Please review the project documentation and ensure your code aligns with the existing project structure, before starting your work on the issue. If you are working on a model, consider adding a `model_details` function to provide additional insights into the model being implemented.

**Comment by yashasvini121** [comment]
Hey @akarshghildyal, please include the estimated time you require for this. Thanks for catching this bug—I’m not sure how I missed it!

**Comment by akarshghildyal** [comment]
@yashasvini121 Hello! I'll do it by tomorrow morning 4, should be a small fix. Thanks.
