### ISSUE TITLE
Developing a Machine learning model for Loan Eligibility Estimator

### ISSUE THREAD

**Issue by Harshitha-Annam** [yashasvini121/predictive-calc#83]
I have seen that there is currently a placeholder logic for Loan Eligibility Estimator, So, I want to develop a new Machine Learning Model for this. Could you please Assign this issue for me ?

- [x] I am a GSSOC Extd Contributor.
- [x] Hacktoberfest
- [x] I have read through the current issues

**Comment by yashasvini121** [comment]
This issue is already assigned to somebody else. #5
