### ISSUE TITLE
Submit new Model Issue Template

### ISSUE THREAD

**Issue by Coreharshit** [yashasvini121/predictive-calc#9]
Problem Description:
Developing new model for enhancing the accuracy of our model. 

Model Description:
using logistic regression model for training and development of relationship between varies factors .

Expected Outcome:
Enhanced accuracy upto 90% 

i would be very thankful to you if you allow me to work on this issue

**Comment by yashasvini121** [comment]
Hey @Coreharshit,
Thanks for your interest! However, you need to be more specific about the problem you’re planning to work on.
