### ISSUE TITLE
Model to detect whether uploaded pdf contains malware or not

### ISSUE THREAD

**Issue by DarshAgrawal14** [yashasvini121/predictive-calc#93]
Overview
We need to create a machine learning model capable of analyzing uploaded PDF files to determine if they contain malware. This model will enhance our system's security by preventing malicious PDFs from being processed or accessed by users.

Objectives
To build a robust model that accurately classifies PDF files as either 'malware' or 'safe'.
To ensure the model can handle various types of PDF files and different forms of embedded threats.

**Comment by yashasvini121** [comment]
Sure @DarshAgrawal14, go ahead, please mention the estimated time required for this, and please go through the [project structure](https://github.com/yashasvini121/predictive-calc/blob/master/docs/project-structure.md) and the [tutorial](https://github.com/yashasvini121/predictive-calc/blob/master/docs/tutorial).

**Comment by DarshAgrawal14** [comment]
got it  , I think i can complete it by day after tomorrow .

**Comment by DarshAgrawal14** [comment]
@yashasvini121 , please let me know if any further changes are needed. Otherwise, I would appreciate it if you could merge the PR.
