### ISSUE TITLE
Add feedback option button

### ISSUE THREAD

**Issue by Aditijainnn** [yashasvini121/predictive-calc#95]
🌟 **Is your feature request related to a problem?**:

![image](https://github.com/user-attachments/assets/d93eeef3-2049-455e-b737-008f5d69756c)
in this adding feedback option also so that user can interact more

**To be Mentioned while taking the issue**:
- What is your participant role? 
- gssoc ext and hacktoberfest

**Note:**
- Please review the project documentation and ensure your code aligns with the project structure. If applicable, consider adding a `model_details` function for additional insights.
- Prefer using a new branch to resolve the issue, as it helps keep the main branch stable and makes it easier to manage and review your changes.

**Comment by yashasvini121** [comment]
This feature isn't required right now.
